name: CI & Package

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build (TS)
        run: npm run build
      - name: Verify checksums
        run: npm run verify:checksums

  package-on-release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: build-and-verify
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build (TS)
        run: npm run build
      - name: Package .mcaddon
        run: npm run package:mcaddon
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lbff-inventory-sorter-mcaddon
          path: dist/lbff_inventory_sorter.mcaddon
